/**
 * ASTRAL_CORE 2.0 Database Utilities - Volunteer Operations
 * Utility functions for volunteer-related database operations
 */
export declare function createVolunteer(data: {
    anonymousId: string;
    specializations?: string[];
    languages?: string[];
    timezone?: string;
}): Promise<{
    id: string;
    anonymousId: string;
    status: import("packages/database/generated/client").$Enums.VolunteerStatus;
    languages: string | null;
    timezone: string | null;
    trainingHours: number;
    certifications: string | null;
    specializations: string | null;
    backgroundCheck: import("packages/database/generated/client").$Enums.VerificationStatus;
    sessionsCount: number;
    hoursVolunteered: number;
    averageRating: number | null;
    responseRate: number;
    isActive: boolean;
    currentLoad: number;
    maxConcurrent: number;
    schedule: import("packages/database/generated/client/runtime/library").JsonValue | null;
    lastActive: Date;
    burnoutScore: number;
    needsSupport: boolean;
    emergencyResponder: boolean;
    emergencyAvailable: boolean;
} | {
    id: string;
    anonymousId: string;
    status: import("packages/database/generated/client").$Enums.VolunteerStatus;
    languages: string | null;
    timezone: string | null;
    trainingHours: number;
    certifications: string | null;
    specializations: string | null;
    backgroundCheck: import("packages/database/generated/client").$Enums.VerificationStatus;
    sessionsCount: number;
    hoursVolunteered: number;
    averageRating: number | null;
    responseRate: number;
    isActive: boolean;
    currentLoad: number;
    maxConcurrent: number;
    schedule: import("packages/database/generated/client/runtime/library").JsonValue | null;
    lastActive: Date;
    burnoutScore: number;
    needsSupport: boolean;
    emergencyResponder: boolean;
    emergencyAvailable: boolean;
}>;
export declare function updateVolunteerStatus(volunteerId: string, status: string): Promise<{
    id: string;
    anonymousId: string;
    status: import("packages/database/generated/client").$Enums.VolunteerStatus;
    languages: string | null;
    timezone: string | null;
    trainingHours: number;
    certifications: string | null;
    specializations: string | null;
    backgroundCheck: import("packages/database/generated/client").$Enums.VerificationStatus;
    sessionsCount: number;
    hoursVolunteered: number;
    averageRating: number | null;
    responseRate: number;
    isActive: boolean;
    currentLoad: number;
    maxConcurrent: number;
    schedule: import("packages/database/generated/client/runtime/library").JsonValue | null;
    lastActive: Date;
    burnoutScore: number;
    needsSupport: boolean;
    emergencyResponder: boolean;
    emergencyAvailable: boolean;
} | {
    id: string;
    anonymousId: string;
    status: import("packages/database/generated/client").$Enums.VolunteerStatus;
    languages: string | null;
    timezone: string | null;
    trainingHours: number;
    certifications: string | null;
    specializations: string | null;
    backgroundCheck: import("packages/database/generated/client").$Enums.VerificationStatus;
    sessionsCount: number;
    hoursVolunteered: number;
    averageRating: number | null;
    responseRate: number;
    isActive: boolean;
    currentLoad: number;
    maxConcurrent: number;
    schedule: import("packages/database/generated/client/runtime/library").JsonValue | null;
    lastActive: Date;
    burnoutScore: number;
    needsSupport: boolean;
    emergencyResponder: boolean;
    emergencyAvailable: boolean;
}>;
export declare function assignVolunteerToSession(sessionId: string, volunteerId: string): Promise<{
    id: string;
    anonymousId: string;
    status: import("packages/database/generated/client").$Enums.VolunteerStatus;
    languages: string | null;
    timezone: string | null;
    trainingHours: number;
    certifications: string | null;
    specializations: string | null;
    backgroundCheck: import("packages/database/generated/client").$Enums.VerificationStatus;
    sessionsCount: number;
    hoursVolunteered: number;
    averageRating: number | null;
    responseRate: number;
    isActive: boolean;
    currentLoad: number;
    maxConcurrent: number;
    schedule: import("packages/database/generated/client/runtime/library").JsonValue | null;
    lastActive: Date;
    burnoutScore: number;
    needsSupport: boolean;
    emergencyResponder: boolean;
    emergencyAvailable: boolean;
} | {
    id: string;
    anonymousId: string;
    status: import("packages/database/generated/client").$Enums.VolunteerStatus;
    languages: string | null;
    timezone: string | null;
    trainingHours: number;
    certifications: string | null;
    specializations: string | null;
    backgroundCheck: import("packages/database/generated/client").$Enums.VerificationStatus;
    sessionsCount: number;
    hoursVolunteered: number;
    averageRating: number | null;
    responseRate: number;
    isActive: boolean;
    currentLoad: number;
    maxConcurrent: number;
    schedule: import("packages/database/generated/client/runtime/library").JsonValue | null;
    lastActive: Date;
    burnoutScore: number;
    needsSupport: boolean;
    emergencyResponder: boolean;
    emergencyAvailable: boolean;
}>;
export declare function recordVolunteerSession(data: {
    volunteerId: string;
    sessionType: string;
    crisisSessionId?: string;
}): Promise<{
    id: string;
    startedAt: Date;
    endedAt: Date | null;
    outcome: import("packages/database/generated/client").$Enums.SessionOutcome | null;
    responseTime: number | null;
    volunteerId: string;
    duration: number | null;
    sessionType: import("packages/database/generated/client").$Enums.VolunteerSessionType;
    crisisSessionId: string | null;
    userSatisfaction: number | null;
} | {
    id: string;
    startedAt: Date;
    endedAt: Date | null;
    outcome: import("packages/database/generated/client").$Enums.SessionOutcome | null;
    responseTime: number | null;
    volunteerId: string;
    duration: number | null;
    sessionType: import("packages/database/generated/client").$Enums.VolunteerSessionType;
    crisisSessionId: string | null;
    userSatisfaction: number | null;
}>;
//# sourceMappingURL=volunteer.d.ts.map